### ISSUE TITLE
如何在typescript项目中使用

### ISSUE THREAD

**Issue by zhixinpeng** [theajack/mp-mixin#1]
我使用微信小程序的typesciprt模板，引入mp-mixin之后，wx的声明中不会注入那三个方法。

能否兼容一下typescript项目

**Comment by theajack** [comment]
> 我使用微信小程序的typesciprt模板，引入mp-mixin之后，wx的声明中不会注入那三个方法。
> 
> 能否兼容一下typescript项目

@zhixinpeng 
已增加 微信小程序 ts模板的类型扩展，请升级到 0.0.5 版本使用
