### ISSUE TITLE
为何不支持Page和Component状态共享？

### ISSUE THREAD

**Issue by zhixinpeng** [theajack/mp-mixin#2]
一般跨页面的状态都会放在一些公共的组件内，各页面共同组件之间共享一个状态，与各自Page产生交互改变状态。
如果只是Page之间共享的话，实际应用起来还是会比较麻烦。

PS：不知道如何进入这个项目的调试开发环境，如果可以，希望能提交pull request。

**Comment by theajack** [comment]
@zhixinpeng 

目前确实没有支持组件，后续可以考虑加上

至于开发环境，如果是ts小程序 把该项目clone到你的小程序中，然后引入该项目就可以
如果是js小程序，那么可能要加一个webpack打包

**Comment by theajack** [comment]
不过有个问题啊 组件用 properties 可以和Page交互，所以可以借助Page之间data共享，来实现组件状态变更

如果这里加入组件的data与Page的data共享，可能状态就会很乱

不知你这里说的应用场景是怎样的 可否详细描述一下

**Comment by zhixinpeng** [comment]
我这里有个场景，一个音频播放器，在各个页面都固定在底部，这个播放器将会封装成一个公共组件，Page仅需要操作背景音频的API即可。

不过这需要一个方法可以触发全局Store的变更并触发UI更新，目前好像并不支持。

这个 Component 需要维护一个全局状态，比如播放进度，当前播放，播放列表等。

这种场景下，只需要各个页面的 Audio Component 保持状态同步即可。

可能和你一开始的构想有所冲突，我这个场景下的目标是维护一个Store，这个Store的数据可以注入到Page和Component的Data中，状态保持同步并触发UI更新，有点类Redux了。

我看源码是主要通过重写setData函数来实现的，这个需要基础库2.2.3以上的支持。目前来说不会出现问题。[来源](https://developers.weixin.qq.com/community/develop/doc/00042a60da0f58936287af95756c00?_at=1562576927111)

我为何会对这个插件感兴趣呢？

1、不需要改变声明Page和Component的方法，与原生保持一致，不需要使用额外的API，可以直接使用小程序提供的声明文件
2、支持Typescript的微信小程序状态同步插件，只有这个
3、其他同类插件年久失修，大都不再维护
4、现在开发小程序大都使用框架，比如Taro等，有非常完善的方案，针对原生小程序特别是Typescript版本方案的，越来越少。而全局状态管理一直是小程序的痛点，官方也不支持，但又非常常用。

写的有点多，还望见谅！

**Comment by theajack** [comment]
感谢你的关注和建议，这个我Component的支持我会尽快加上的，本来开发之初有这个打算，只是比较忙，没有开发。

目前对于你这个场景，我觉得通过Page共享状态然后传递给组件也是可以做到的，不过稍显麻烦，需要写多一点代码以及考虑父子组件通信。
@zhixinpeng

**Comment by theajack** [comment]
@zhixinpeng 
已经加了组件mixin，另外优化了事件机制，减少了setData调用
请升级到1.0.0 使用

**Comment by theajack** [comment]
使用 1.0.1 吧 删掉了两句调试的log

**Comment by zhixinpeng** [comment]
感谢
